[package]
name = "ascii-art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttype = "0.9.3"
image = "0.24.6"
csv = "1.2.1"
nshare = "0.9.0"
ndarray = "0.15.6"
